services:
  drivenops_db:
    image: postgres
    container_name: drivenops_db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env
    volumes:
      - drivenops-db:/var/lib/postgres/data

  node_drivenops_app:
    container_name: node_drivenops_app
    build: ./back-end
    image: node_drivenops_app_image
    ports:
      - 5000:5000
    depends_on:
      - drivenops_db
    env_file:
      - ./back-end/.env

  react_drivenops_app:
    container_name: react_drivenops_app
    build: ./front-end
    image: react_drivenops_app_image
    volumes:
      - build_react:/var/www/html

  nginx_drivenops_app:
    container_name: nginx_drivenops_app
    build: ./nginx
    image: nginx_drivenops_app_image
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - react_drivenops_app
      - node_drivenops_app
      - drivenops_db
volumes:
  drivenops-db:
  build_react:
